### ISSUE TITLE
proto: `std` feature is broken

### ISSUE THREAD

**Issue by tony-iqlusion** [informalsystems/tendermint-rs#1454]
### What went wrong?

The `std` feature added in #1452 doesn't work. /cc @romac

### Steps to reproduce

```console
$ cd proto
$ cargo test --features std
```

This results in the following compile errors:

```
$ cargo test --features std                                                                                       130 ↵
   Compiling tendermint-proto v0.39.0 (/Users/tarcieri/src/tendermint-rs/proto)
error[E0433]: failed to resolve: use of undeclared crate or module `std`
   --> proto/src/google/protobuf/timestamp.rs:105:11
    |
105 | impl From<std::time::SystemTime> for Timestamp {
    |           ^^^ use of undeclared crate or module `std`

error[E0433]: failed to resolve: use of undeclared crate or module `std`
   --> proto/src/google/protobuf/timestamp.rs:106:26
    |
106 |     fn from(system_time: std::time::SystemTime) -> Timestamp {
    |                          ^^^ use of undeclared crate or module `std`

error[E0433]: failed to resolve: use of undeclared crate or module `std`
   --> proto/src/google/protobuf/timestamp.rs:107:65
    |
107 |         let (seconds, nanos) = match system_time.duration_since(std::time::UNIX_EPOCH) {
    |                                                                 ^^^ use of undeclared crate or module `std`

error[E0433]: failed to resolve: use of undeclared crate or module `std`
   --> proto/src/google/protobuf/timestamp.rs:155:29
    |
155 | impl TryFrom<Timestamp> for std::time::SystemTime {
    |                             ^^^ use of undeclared crate or module `std`
```

(truncated)

These errors don't occur when `cargo test --all-features` is used, hence why it wasn't caught by CI, ostensibly because when it's compiled with that some other crate is linking `std`.

It would be good in CI to explicitly test the `std` feature in isolation.

### Definition of "done"

`cargo test --features std` compiles in isolation.

**Comment by romac** [comment]
Thanks to `cargo-hack` I realized there are other features which cannot be used in isolation, I've pushed fixes for all them in #1455.
